#!/bin/bash

module load system/Python-3.6.3

cd /home/knam/work/WG_phasing/data_prep/simulation/fasta/diploid

python /home/knam/save/programs/neat-genreads-master/gen_reads.py -r s2.fa.gz -R 150 -o ../../../Illumina/i2 --pe 300 30 -c 20 -M 0
